fix: pipe output to files to avoid buffering and I/O ops, weird timeouts in plugin-packaging
salesforcecli/cli-plugins-testkit pull request #387
Opened 2023-01-24 21:54 UTC by WillieRuemmele

[this](https://github.com/salesforcecli/plugin-packaging/pull/198/commits/e68a85e14431b7d1b462bd691729620d3760c6bf) commit in plugin-packaging started seeing weird timeouts like 
```
{
        "Id": "08c4p000000081bAAA",
        "Status": "Success",
        "Package2Id": "0Ho4p00000003x6CAA",
        "Package2VersionId": "05i4p00000007azAAA",
        "SubscriberPackageVersionId": "04t4p000001zyDGAAY",
        "Tag": null,
        "Branch": null,
        "Error": [],
        "CreatedDate": "2023-01-17 09:16",
        "HasMetadataRemoved": false,
        "CreatedBy": "00546000002jDFFAA2"
      },
      {
        "Id": "08c4p00000008
  stderr=Error: timed out
      at Object.error (node_modules/@oclif/core/lib/errors/index.js:28:15)
      at /Users/william.ruemmele/projects/oss/plugin-packaging/node_modules/@oclif/core/lib/cli-ux/index.js:25:66
      at async flush (node_modules/@oclif/core/lib/cli-ux/index.js:124:9)
  
      at getExitCodeError (/Users/william.ruemmele/projects/oss/cli-plugins-testkit/src/execCmd.ts:104:10)
      at execCmdSync (/Users/william.ruemmele/projects/oss/cli-plugins-testkit/src/execCmd.ts:170:11)
      at execCmd (/Users/william.ruemmele/projects/oss/cli-plugins-testkit/src/execCmd.ts:248:12)
      at Context.<anonymous> (test/commands/package/packageVersion.nut.ts:182:29)
      at processImmediate (node:internal/timers:471:21)
```
it was like it was timing out while printing to the `shelljs.exec` method, trying increasing the Buffer size and timeout had no affect. It was very weird because they were passing on windows, but the linux vm was almost too fast??

In an effort to reduce operations, Pete suggested piping the command output to a file, and then reading it back into memory. When implemented in the plugin this resolved the issue.

We can move this into the NUTs library to help all NUTs

2023-01-24 22:08 UTC, peternhale requested changes

2023-01-24 22:08 UTC, peternhale commented on src/execCmd.ts
> +import { join, join as pathJoin, resolve as pathResolve } from 'path';
@WillieRuemmele join is already imported as `pathJoin`

2023-01-24 22:08 UTC, peternhale commented on src/execCmd.ts
> +  result.shellOutput.code = (shelljs.exec(`${cmd} > ${commandFile} 2> ${stderrFile} `, cmdOptions) as ShellString).code;
``` suggestion
  result.shellOutput.code = (shelljs.exec(`${cmd} 1> ${commandFile} 2> ${stderrFile} `, cmdOptions) as ShellString).code;
```

2023-01-24 22:08 UTC, peternhale commented on src/execCmd.ts
> +    shelljs.exec(`${cmd} > ${commandFile} 2> ${stderrFile}`, cmdOptions, callback);
``` suggestion
    shelljs.exec(`${cmd} 1> ${commandFile} 2> ${stderrFile}`, cmdOptions, callback);
```

2023-01-24 22:12 UTC, shetzel commented on src/execCmd.ts
> +const genFileName = (name: string): string => `${name}-${Math.random()}.txt`;
You could instead use `genUniqueString()` function from this lib.

2023-01-25 12:27 UTC, peternhale requested changes

2023-01-25 12:27 UTC, peternhale commented on test/unit/execCmd.test.ts
> +    expect(execStub.args[0][0]).to.include('> command');
@WillieRuemmele I know this works, but should these be changed to `1> command` for completeness?

2023-01-31 17:54 UTC, shetzel approved these changes

2023-01-31 18:02 UTC, merged