feat: add access token hub auth strategy
salesforcecli/cli-plugins-testkit pull request #90
Opened 2021-05-12 14:40 UTC by peternhale

@W-8066452@

2021-05-12 15:57 UTC, shetzel requested changes
The README.md and SAMPLES.md need to be updated as well, particularly the environment variables sections.

2021-05-12 15:57 UTC, shetzel commented on test/unit/hubAuth.test.ts
> +  it('auths from access token');
Are we going to ignore these unit tests forever?  Even having NUTs for this would be something.  Right now there's nothing.

2021-05-12 15:57 UTC, shetzel commented on src/hubAuth.ts
> +
Can you update the public jsdoc for the testkitHubAuth function?

2021-05-13 11:37 UTC, peternhale reviewed
Will add jsdoc

2021-05-13 19:52 UTC, shetzel approved these changes

2021-05-13 20:02 UTC, merged